### kanslayer

In [29]:
%reload_ext autoreload
import torch
from tot.kans import KANLayer

In [36]:
model = KANLayer(in_dim=3,out_dim=2,num=1,base_fun=torch.nn.Sil)
x = torch.randn(2,3)
y, preacts, postacts, postspline = model(x)
y, preacts, postacts, postspline

(tensor([[-0.5646, -0.5540],
         [ 2.4432,  2.4118]], grad_fn=<SumBackward1>),
 tensor([[[-2.8988, -0.2657, -0.9008],
          [-2.8988, -0.2657, -0.9008]],
 
         [[ 0.3424,  0.1560,  2.3738],
          [ 0.3424,  0.1560,  2.3738]]]),
 tensor([[[-0.1450, -0.1315, -0.2880],
          [-0.1441, -0.1401, -0.2698]],
 
         [[ 0.2163,  0.0852,  2.1417],
          [ 0.2184,  0.0492,  2.1442]]], grad_fn=<ViewBackward0>),
 tensor([[[ 0.0063, -0.0162, -0.0278],
          [ 0.0073, -0.0248, -0.0096]],
 
         [[ 0.0161,  0.0011, -0.0298],
          [ 0.0182, -0.0349, -0.0274]]], grad_fn=<ReshapeAliasBackward0>))

In [40]:
print(model.base_fun)

SiLU()
